[build]
  command = "npm run build"
  functions = "functions"

[functions]
  included_files = ["_layout/*","ads/*","assets/*","*"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/core/:splat"
  status = 200
  force = true
